# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('user_id', models.CharField(max_length=20)),
                ('image_url', models.CharField(default='http://placehold.it/350x150', max_length=200)),
            ],
        ),
    ]
